[grpc]
address = "0.0.0.0:27000"

[grpc.services.storageprovider]
driver = "localhome"
mount_path = "/home"
mount_id = "123e4567-e89b-12d3-a456-426655440000"
data_server_url = "http://localhost:27001/data"

[http]
address = "0.0.0.0:27001"

[http.services.dataprovider]
driver = "localhome"
