[grpc]
address = "0.0.0.0:27000"

[grpc.services.storageprovider]
driver = "localhome"
mount_path = "/home"
mount_id = "44aba51f-a122-48b0-9e86-e32e076b1a34"
data_server_url = "http://localhost:27001/data"

[http]
address = "0.0.0.0:27001"

[http.services.dataprovider]
driver = "localhome"
