[grpc]
address = "0.0.0.0:28000"

[grpc.services.storageprovider]
driver = "local"
mount_path = "/reva"
mount_id = "123e4567-e89b-12d3-a456-426655440000"
data_server_url = "http://localhost:28001/data"

[http]
address = "0.0.0.0:28001"

[http.services.dataprovider]
driver = "local"
