[grpc]
address = "0.0.0.0:27000"

[grpc.services.storageprovider]
driver = "localhome"
data_server_url = "http://localhost:27001/data"

[http]
address = "0.0.0.0:27001"

[http.services.dataprovider]
driver = "localhome"
