[grpc]
address = "0.0.0.0:28000"

[grpc.services.storageprovider]
driver = "local"
data_server_url = "http://localhost:28001/data"

[http]
address = "0.0.0.0:28001"

[http.services.dataprovider]
driver = "local"
