[grpc]
address = "0.0.0.0:18000"

[grpc.services.storageprovider]
driver = "local"
data_server_url = "http://localhost:18001/data"

[http]
address = "0.0.0.0:18001"

[http.services.dataprovider]
driver = "local"
