// Copyright 2018-2022 CERN
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// In applying this license, CERN does not waive the privileges and immunities
// granted to it by virtue of its status as an Intergovernmental Organization
// or submit itself to any jurisdiction.

// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	events "github.com/opencloud-eu/reva/v2/pkg/events"
	mock "github.com/stretchr/testify/mock"

	raw "github.com/opencloud-eu/reva/v2/pkg/events/raw"
)

// Stream is an autogenerated mock type for the Stream type
type Stream struct {
	mock.Mock
}

type Stream_Expecter struct {
	mock *mock.Mock
}

func (_m *Stream) EXPECT() *Stream_Expecter {
	return &Stream_Expecter{mock: &_m.Mock}
}

// Consume provides a mock function with given fields: group, evs
func (_m *Stream) Consume(group string, evs ...events.Unmarshaller) (<-chan raw.Event, error) {
	var tmpRet mock.Arguments
	if len(evs) > 0 {
		tmpRet = _m.Called(group, evs)
	} else {
		tmpRet = _m.Called(group)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 <-chan raw.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(string, ...events.Unmarshaller) (<-chan raw.Event, error)); ok {
		return rf(group, evs...)
	}
	if rf, ok := ret.Get(0).(func(string, ...events.Unmarshaller) <-chan raw.Event); ok {
		r0 = rf(group, evs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan raw.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(string, ...events.Unmarshaller) error); ok {
		r1 = rf(group, evs...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Stream_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type Stream_Consume_Call struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - group string
//   - evs ...events.Unmarshaller
func (_e *Stream_Expecter) Consume(group interface{}, evs ...interface{}) *Stream_Consume_Call {
	return &Stream_Consume_Call{Call: _e.mock.On("Consume",
		append([]interface{}{group}, evs...)...)}
}

func (_c *Stream_Consume_Call) Run(run func(group string, evs ...events.Unmarshaller)) *Stream_Consume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]events.Unmarshaller, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(events.Unmarshaller)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *Stream_Consume_Call) Return(_a0 <-chan raw.Event, _a1 error) *Stream_Consume_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Stream_Consume_Call) RunAndReturn(run func(string, ...events.Unmarshaller) (<-chan raw.Event, error)) *Stream_Consume_Call {
	_c.Call.Return(run)
	return _c
}

// NewStream creates a new instance of Stream. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStream(t interface {
	mock.TestingT
	Cleanup(func())
}) *Stream {
	mock := &Stream{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
