[core]
log_file = "stderr"
log_mode = "dev"
max_cpus = "100%"
tracing_enabled = true
disable_http = true

[log]
level = "debug"
mode = "console"

[grpc]
network = "tcp"
address = "0.0.0.0:10000"
enabled_services = ["gatewaysvc"]

[grpc.services.gatewaysvc]
storageregistrysvc = "localhost:9999"
authsvc = "localhost:9999"
