version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
  commit-message:
    prefix: "[Build-deps]"
  open-pull-requests-limit: 10
  reviewers:
  - ishank011
  - SamuAlfageme
