---
kind: pipeline
type: docker
name: build-on-push

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: golang:1.13
  commands:
    - make ci

- name: publish-docker-reva-latest
  pull: always
  image: plugins/docker
  settings:
    repo: cs3org/reva
    tags: latest
    dockerfile: Dockerfile.reva
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password

- name: publish-docker-revad-latest
  pull: always
  image: plugins/docker
  settings:
    repo: cs3org/revad
    tags: latest
    dockerfile: Dockerfile.revad
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
