---
kind: pipeline
type: docker
name: build-and-publish-docker

platform:
  os: linux
  arch: amd64

trigger:
  branch:
  - master
  event:
    exclude:
    - pull_request
    - tag
    - promote
    - rollback
steps:
- name: license-scan
  image: golang:1.13
  environment:
    FOSSA_API_KEY:
      from_secret: fossa_api_key
  commands:
    - wget -qO- https://github.com/fossas/fossa-cli/releases/download/v1.0.11/fossa-cli_1.0.11_linux_amd64.tar.gz | tar xvz -C /go/bin/ 
    - /go/bin/fossa analyze 


- name: build
  image: golang:1.13
  commands:
    - make ci

- name: lint
  image: golangci/golangci-lint:v1.21.0
  commands:
    - golangci-lint run

- name: license-check
  image: golang:1.13
  environment:
    FOSSA_API_KEY:
      from_secret: fossa_api_key
  commands:
    - wget -qO- https://github.com/fossas/fossa-cli/releases/download/v1.0.11/fossa-cli_1.0.11_linux_amd64.tar.gz | tar xvz -C /go/bin/ 
    - /go/bin/fossa test

- name: publish-docker-reva-latest
  pull: always
  image: plugins/docker
  settings:
    repo: cs3org/reva
    tags: latest
    dockerfile: Dockerfile.reva
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password

- name: publish-docker-revad-latest
  pull: always
  image: plugins/docker
  settings:
    repo: cs3org/revad
    tags: latest
    dockerfile: Dockerfile.revad
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password

---
kind: pipeline
type: docker
name: build-only

platform:
  os: linux
  arch: amd64

trigger:
  event:
    include:
    - pull_request

steps:
- name: license-scan
  image: golang:1.13
  environment:
    FOSSA_API_KEY:
      from_secret: fossa_api_key
  commands:
    - wget -qO- https://github.com/fossas/fossa-cli/releases/download/v1.0.11/fossa-cli_1.0.11_linux_amd64.tar.gz | tar xvz -C /go/bin/ 
    - /go/bin/fossa analyze 

- name: build
  image: golang:1.13
  commands:
    - make ci

- name: lint
  image: golangci/golangci-lint:v1.21.0
  commands:
    - golangci-lint run

- name: license-check
  image: golang:1.13
  environment:
    FOSSA_API_KEY:
      from_secret: fossa_api_key
  commands:
    - wget -qO- https://github.com/fossas/fossa-cli/releases/download/v1.0.11/fossa-cli_1.0.11_linux_amd64.tar.gz | tar xvz -C /go/bin/ 
    - /go/bin/fossa test
