issues:
  exclude-rules:
    - path: internal/http/interceptors/log/log.go
      text: "SA1019:"
      linters:
        - staticcheck
    - path: pkg/utils/utils.go
      text: "SA1019:"
      linters:
        - staticcheck
    # Exclude scopelint for tests files because of https://github.com/kyoh86/scopelint/issues/4
    - path: _test\.go
      linters:
        - scopelint
linters:
  enable:
    - bodyclose
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - depguard
    - golint
    - goimports
    - unconvert
    - scopelint
    - maligned
    - misspell
    - gocritic
    - prealloc
    #- gosec
