# This auth.toml config file will start a reva service that:
# - handles authentication, users and user preferences
# - serves the grpc services on port 18000
[core]
max_cpus = "2"
disable_http = true

[log]
level = "debug"

[grpc]
network = "tcp"
address = "0.0.0.0:18000"
enabled_services = [
    "authprovider", # provides basic auth
    "userprovider", # provides user matadata (used to look up email, displayname etc after a login)
    "preferences",  # provides user preferences
]
enabled_interceptors = ["auth"]

[grpc.services.authprovider]
auth_manager = "json"
userprovidersvc = "localhost:18000"

[grpc.services.authprovider.auth_managers.json]
users = "./examples/separate/users.demo.json"

[grpc.services.userprovider]
driver = "json"

[grpc.services.userprovider.drivers.json]
users = "./examples/separate/users.demo.json"

[grpc.interceptors.auth]
token_manager = "jwt"
skip_methods = [
    # we need to allow calls that happen during authentication
	"/cs3.authproviderv0alpha.AuthProviderService/Authenticate",
	"/cs3.userproviderv0alpha.UserProviderService/GetUser",
]

[grpc.interceptors.auth.token_managers.jwt]
secret = "Pive-Fumkiu4"
