# This frontend.toml config file will start a reva service that:
# - serves as the entypoint for all legacy owncloud requests
# - serves http endpoints on port 20080
#   - /owncloud - ocdav
#   - /ocs - ocs
#   - TODO ocm
[core]
max_cpus = "2"

[log]
level = "debug"

[grpc]
address = "0.0.0.0:18001"
enabled_services = [
    "authprovider"
]

[grpc.services.authprovider]
auth_manager = "oidc"
userprovidersvc = "http://localhost:20080"

[grpc.services.authprovider.auth_managers.oidc]
provider = "http://localhost:20080"
insecure = true
# credentials used for the introspection endpoint with basic auth
# also rate limit the endpoint: https://tools.ietf.org/html/rfc7662#section-4
# TODO(jfd) introduce rate limits
client_id = "reva"
client_secret = "foobar"

[http]
enabled_services = ["wellknown", "oidcprovider", "ocdav", "ocs"]
enabled_middlewares = ["cors", "auth"]
address = "0.0.0.0:20080"

[http.middlewares.auth]
gateway = "localhost:19000"
auth_type = "oidc"
credential_strategy = "oidc"
token_strategy = "header"
token_writer = "header"
token_manager = "jwt"
skip_methods = [
    "/owncloud/status.php",
	"/oauth2",
	"/oauth2/auth", 
	"/oauth2/token",
	# TODO protect the introspection endpoint from external requests.
	# should only be reachable by internal services, which is why the
	# oidc-provider.toml has clientid and secret that are used for a basic auth
	"/oauth2/introspect",
	"/oauth2/userinfo",
	"/oauth2/sessions",
	"/.well-known/openid-configuration",
]

[http.middlewares.auth.token_managers.jwt]
secret = "Pive-Fumkiu4"

[http.middlewares.cors]
allowed_origins = ["*"]
allowed_methods = ["OPTIONS", "GET", "PUT", "POST", "DELETE", "MKCOL", "PROPFIND", "PROPPATCH", "MOVE", "COPY", "REPORT", "SEARCH"]
allowed_headers = ["Origin", "Accept", "Depth", "Content-Type", "X-Requested-With", "Authorization", "Ocs-Apirequest", "If-None-Match"]
allow_credentials = true
options_passthrough = false

[http.services.wellknown]
issuer = "http://localhost:20080"
authorization_endpoint = "http://localhost:20080/oauth2/auth"
token_endpoint = "http://localhost:20080/oauth2/token" 
#jwks_uri = ""
revocation_endpoint = "http://localhost:20080/oauth2/auth"
introspection_endpoint = "http://localhost:20080/oauth2/introspect"
userinfo_endpoint = "http://localhost:20080/oauth2/userinfo"
#end_session_endpoint = 

[http.services.oidcprovider]
prefix = "oauth2"
gateway = "localhost:19000"
auth_type = "basic"
issuer = "http://localhost:20080"

[http.services.oidcprovider.clients.phoenix]
id = "phoenix"
redirect_uris = ["http://localhost:8300/oidc-callback.html", "http://localhost:8300/"]
grant_types = ["implicit", "refresh_token", "authorization_code", "password", "client_credentials"]
response_types = ["code"] # use authorization code flow, see https://developer.okta.com/blog/2019/05/01/is-the-oauth-implicit-flow-dead for details
scopes = ["openid", "profile", "email", "offline"]
public = true # force PKCS for public clients

[http.services.oidcprovider.clients.reva]
id = "reva"
grant_types = ["implicit", "refresh_token", "authorization_code", "password", "client_credentials"]
response_types = ["code"] # use authorization code flow
# private clients can use a secret
client_secret = "$2a$10$IxMdI6d.LIRZPpSfEwNoeu4rY3FhDREsxFJXikcgdRRAStxUlsuEO"  # = "foobar"
scopes = ["openid", "profile", "email", "offline"]

# to debug the oidc provider allow https://oidcdebugger.com
[http.services.oidcprovider.clients.oidcdebugger]
id = "oidcdebugger"
redirect_uris = ["https://oidcdebugger.com/debug"]
grant_types = ["implicit", "refresh_token", "authorization_code", "password", "client_credentials"]
response_types = ["id_token token", "code"]
client_secret = "$2a$10$IxMdI6d.LIRZPpSfEwNoeu4rY3FhDREsxFJXikcgdRRAStxUlsuEO"  # = "foobar"
scopes = ["openid", "profile", "email", "offline"]

[http.services.ocdav]
prefix = ""
chunk_folder = "/var/tmp/revad/chunks"
# for user lookups
gateway = "localhost:19000"

[http.services.ocs]
# prefix = "ocs"
# for user lookups and sharing
gateway = "localhost:19000"
