# This users.toml config file will start a reva service that:
# - handles user metadata and user preferences
# - serves the grpc services on port 18000
[core]
max_cpus = "2"
disable_http = true

[log]
level = "debug"

[grpc]
network = "tcp"
address = "0.0.0.0:18000"
enabled_services = [
    "approvider",
    "userprovider", # provides user matadata (used to look up email, displayname etc after a login)
    "preferences",  # provides user preferences
]
enabled_interceptors = ["auth"]

[grpc.services.appprovider]
driver = "demo"

[grpc.services.appprovider.demo]
iframe_ui_provider = "http://localhost:19500/iframeui"

[grpc.services.userprovider]
driver = "json"

[grpc.services.userprovider.drivers.json]
users = "./examples/separate/users.demo.json"

[grpc.interceptors.auth]
token_manager = "jwt"
skip_methods = [
    # we need to allow calls that happen during authentication
	"/cs3.userproviderv0alpha.UserProviderService/GetUser",
]

[grpc.interceptors.auth.token_managers.jwt]
secret = "Pive-Fumkiu4"

# TODO bring back iframe app ui demo
#[http]
#address = "0.0.0.0:19500"
#enabled_services = ["iframeui"]