# This users.toml config file will start a reva service that:
# - handles user metadata and user preferences
# - serves the grpc services on port 18000
[core]
max_cpus = "2"
disable_http = true

[log]
level = "debug"

[grpc]
network = "tcp"
address = "0.0.0.0:18000"
enabled_interceptors = ["auth"]
enabled_services = [
    "authprovider", # provides basic auth
    "userprovider", # provides user matadata (used to look up email, displayname etc after a login)
    "preferences",  # provides user preferences
]

[grpc.interceptors.auth]
token_manager = "jwt"

[grpc.interceptors.auth.token_managers.jwt]
secret = "Pive-Fumkiu4"

[grpc.services.authprovider]
auth_manager = "json"

[grpc.services.authprovider.auth_managers.json]
users = "users.demo.json"

[grpc.services.userprovider]
driver = "json"

[grpc.services.userprovider.drivers.json]
users = "users.demo.json"
