[shared]
jwt_secret = "Pive-Fumkiu4"
gatewaysvc = "localhost:17000"

[grpc]
address = "0.0.0.0:17000"

[grpc.services.gateway]
ocmproviderauthorizersvc = "localhost:17000"

[grpc.services.ocmproviderauthorizer]
driver = "json"

[grpc.services.ocmproviderauthorizer.drivers.json]
providers = "providers.demo.json"

#[grpc.services.ocmproviderauthorizer.drivers.mentix]
#url = "http://127.0.0.1:9600/mentix/cs3"
#insecure = true
#timeout = 10

[http]
address = "0.0.0.0:9600"

[http.services.meshdirectory]
