# services to enable
[grpc.services.gateway]
[grpc.services.storageregistry]
[grpc.services.storageprovider]
[grpc.services.authregistry]
[grpc.services.usershareprovider]
[grpc.services.publicshareprovider]
[grpc.services.ocmcore]
driver = "json"

[grpc.services.ocmcore.drivers.json]
file = "/var/tmp/reva/shares_server_1.json"

[grpc.services.ocminvitemanager]
driver = "json"

[grpc.services.ocmshareprovider]
driver = "json"

[grpc.services.ocmshareprovider.drivers.json]
file = "/var/tmp/reva/shares_server_1.json"

[http.services.datagateway]
[http.services.dataprovider]
[http.services.prometheus]
[http.services.ocmd]
[http.services.ocdav]
[http.services.ocs]

[grpc.services.authprovider]
auth_manager = "json"

[grpc.services.authprovider.auth_managers.json]
users = "users.demo.json"

[grpc.services.userprovider]
driver = "json"
[grpc.services.groupprovider]
driver = "json"

[grpc.services.groupprovider.drivers.json]
groups = "groups.demo.json"

[grpc.services.userprovider.drivers.json]
users = "users.demo.json"

[grpc.services.ocmproviderauthorizer]
driver = "mentix"

[http.middlewares.providerauthorizer]
driver = "mentix"

[http.middlewares.providerauthorizer.drivers.mentix]
url = "https://localhost:19001/api/mentix/cs3"
insecure = false
timeout = 10
refresh = 900

[grpc.services.ocmproviderauthorizer.drivers.mentix]
url = "https://localhost:19001/api/mentix/cs3"
verify_request_hostname = true
insecure = false
timeout = 10
refresh = 900

[http.services.meshdirectory]
mesh_directory_url = 'http://localhost:19001/meshdir/'