[shared]
gatewaysvc = "localhost:your-revad-gateway-port"

[grpc]
address = "0.0.0.0:12345"

[grpc.services.appprovider]
driver = "wopi"
custom_mime_types_json = "custom-mime-types-demo.json"
mime_types = ["text/markdown", "application/compressed-markdown", "text/plain"]
app_provider_url = "localhost:12345"
language = "en-GB"

[grpc.services.appprovider.drivers.wopi]
iop_secret = "hello"
wopi_url = "http://0.0.0.0:8880/"
app_name = "CodiMD"
app_url = "https://your-codimd-server.org:3000"
app_int_url = "https://your-codimd-server.org:3000"
