[grpc]
address = "0.0.0.0:16000"

[grpc.services.publicstorageprovider]
driver = "localhome"
data_server_url = "http://localhost:16001/data"
gateway_addr = "localhost:19000"

[grpc.services.authprovider]
auth_manager = "publicshares"

[grpc.services.authprovider.auth_managers.publicshares]
gateway_addr = "localhost:19000"
