[shared]
gatewaysvc = "localhost:19000"

[grpc]
address = "localhost:19010"

[grpc.services.storageprovider]
driver = "ocmreceived"
mount_path = "/sciencemesh"
mount_id = "sciencemesh"
expose_data_server = true
data_server_url = "http://localhost:19011/data"

[http]
address = "localhost:19011"

[http.services.dataprovider]
driver = "ocmreceived"
