[shared]
gatewaysvc = "localhost:17000"

[grpc]
address = "localhost:17030"

[grpc.services.authprovider]
auth_manager = "machine"

[grpc.services.authprovider.auth_managers.machine]
api_key = "machine-api-key"
gateway_addr = "localhost:17000"
