# services to enable
[grpc.services.gateway]
[grpc.services.storageregistry]
[grpc.services.storageprovider]
[grpc.services.authprovider]
[grpc.services.authregistry]
[grpc.services.userprovider]
[grpc.services.usershareprovider]
[grpc.services.publicshareprovider]

[http.services.dataprovider]
[http.services.prometheus]

