[core]
log_file = "stderr"
log_mode = "dev"
max_cpus = "100%"
disable_http = true

[log]
level = "debug"
mode = "console"

[grpc]
network = "tcp"
address = "0.0.0.0:9998"
enabled_services = [
"authsvc"
]

[grpc.services.authsvc]
auth_manager = "oidc"

[grpc.services.authsvc.auth_managers.oidc]
provider = "http://0.0.0.0:10000"
insecure = true
client_id = "phoenix"
client_secret = "foobar"
