[core]
max_cpus = "2"

[log]
level = "debug"

[grpc]
network = "tcp"
address = "0.0.0.0:9999"
enabled_services = ["storageprovidersvc", "authsvc", "storageregistrysvc", "preferencessvc", "usershareprovidersvc"]
enabled_interceptors = ["auth"]

[grpc.services.usershareprovidersvc]
driver = "memory"

[grpc.services.storageprovidersvc]
driver = "local"
mount_path = "/"
mount_id = "123e4567-e89b-12d3-a456-426655440000"
# we point to the datagatewaysvc.
data_server_url = "http://localhost:9998/data"

[grpc.services.storageprovidersvc.available_checksums]
md5   = 100
unset = 1000

[grpc.services.storageprovidersvc.drivers.local]
root = "/var/tmp/reva/data"

[grpc.services.authsvc]
auth_manager = "demo"
token_manager = "jwt"
user_manager = "demo"

[grpc.services.authsvc.token_managers.jwt]
secret = "Pive-Fumkiu4"

[grpc.services.storageregistrysvc]
driver = "static"

[grpc.services.storageregistrysvc.drivers.static.rules]
"/" = "localhost:9999"
"123e4567-e89b-12d3-a456-426655440000" = "localhost:9999"

[grpc.interceptors.auth]
token_manager = "jwt"
skip_methods = ["/cs3.authv0alpha.AuthService/GenerateAccessToken", "/cs3.authv0alpha.AuthService/WhoAmI"]

[grpc.interceptors.auth.token_managers.jwt]
secret = "Pive-Fumkiu4"

[http]
address = "0.0.0.0:9998"
enabled_services = ["datasvc"]
enabled_middlewares = ["auth"]

[http.middlewares.auth]
gatewaysvc = "0.0.0.0:9999"
credential_strategy = "basic"
token_strategy = "header"
token_writer = "header"
token_manager = "jwt"
skip_methods = ["/owncloud/status.php", "/metrics"]

[http.middlewares.auth.token_managers.jwt]
secret = "Pive-Fumkiu4"

[http.services.datasvc]
driver = "local"
prefix = "data"
temp_folder = "/var/tmp/"

[http.services.datasvc.drivers.local]
root = "/var/tmp/reva/data"
