[core]
log_file = "stderr"
log_mode = "dev"
max_cpus = "32"

[grpc]
network = "tcp"
address = "0.0.0.0:9999"

[http]
enabled_services = ["prometheussvc", "ocdavsvc"]
network = "tcp"
address = "0.0.0.0:9998"

[http.services.prometheussvc]
prefix = "metrics"

[http.services.ocdavsvc]
prefix = "owncloud"
chunk_folder = "/var/tmp/owncloud/chunks"
storageprovidersvc = "storageprovidersvc:9999"
