[core]
log_file = "stderr"
log_mode = "dev"
max_cpus = "32"

[grpc]
network = "tcp"
address = "0.0.0.0:9999"
enabled_services = ["storagebrokersvc"]

[http]
enabled_services = ["prometheussvc"]
network = "tcp"
address = "0.0.0.0:9998"

[grpc.services.storagebrokersvc]
driver = "static"

[grpc.services.storagebrokersvc.static.rules]
"/" = "storageprovidersvc:9999"
"123e4567-e89b-12d3-a456-426655440000" = "storageprovidersvc:9999"

[http.services.prometheussvc]
prefix = "metrics"
