[core]
log_file = "stderr"
log_mode = "dev"
max_cpus = "32"

[grpc]
network = "tcp"
address = "0.0.0.0:9999"
enabled_services = ["storage_broker_svc"]

[http]
enabled_services = ["prometheus_svc"]
network = "tcp"
address = "0.0.0.0:9998"

[grpc.storage_broker_svc]
driver = "static"

[grpc.storage_broker_svc.static.rules]
"/" = "storageprovidersvc:9999"
"123e4567-e89b-12d3-a456-426655440000" = "storageprovidersvc:9999"

[http.prometheus_svc]
prefix = "metrics"
