[core]
log_file = "stderr"
log_mode = "dev"
max_cpus = "32"

[grpc]
network = "tcp"
address = "0.0.0.0:9999"
enabled_services = ["storageprovidersvc"]

[http]
enabled_services = ["prometheussvc", "webuisvc", "ocdavsvc", "iframeuisvc"]
network = "tcp"
address = "0.0.0.0:9998"

[grpc.services.storageprovidersvc]
driver = "local"
mount_path = "/"
mount_id = "123e4567-e89b-12d3-a456-426655440000"

[grpc.services.storageprovidersvc.drivers.local]

[http.services.prometheussvc]
prefix = "metrics"
