[shared]
jwt_secret = "Pive-Fumkiu4"

# This toml config file will start a reva service that:
# - handles user metadata and user preferences
# - serves the grpc services on port 13000
[grpc]
address = "0.0.0.0:13000"

[grpc.services.authprovider]
auth_manager = "oidcmapping"
[grpc.services.authprovider.auth_managers.json]
users = "users.json"
[grpc.services.authprovider.auth_managers.oidcmapping]
issuer = "https://iam-escape.cloud.cnaf.infn.it/"
# ESCAPE adopted the WLCG groups as group claims
group_claim_label = "wlcg.groups"
userprovidersvc = "0.0.0.0:13000"
# The OIDC users mapping file path
usersmapping = "users-oidcmapping-1.demo.json"

[grpc.services.userprovider]
driver = "json"
[grpc.services.userprovider.drivers.json]
users = "users.demo.json"
