[shared]
jwt_secret = "Pive-Fumkiu4"

# GRPC:
# - serves user and public link shares
[grpc]
address = "0.0.0.0:17000"

[grpc.services.usershareprovider]
driver = "memory"

[grpc.services.publicshareprovider]
driver = "memory"

[grpc.services.publicshareprovider.drivers.json]
file = "/var/tmp/reva/publicshares.json"
