# This storage.toml config file will start a reva service that:
[shared]
jwt_secret = "Pive-Fumkiu4"
gatewaysvc = "localhost:19000"

# - authenticates grpc storage provider requests using the internal jwt token
# - authenticates http upload and download requests requests using basic auth
# - serves the storage provider on grpc port 11000
# - serves http dataprovider for this storage on port 11001
#   - /data - dataprovider: file up and download
[grpc]
address = "0.0.0.0:11000"

# This is a storage provider that grants direct access to the wrapped storage
# we have a locally running dataprovider
[grpc.services.storageprovider]
driver = "owncloud"
mount_path = "/oc"
mount_id = "123e4567-e89b-12d3-a456-426655440000"
expose_data_server = true
data_server_url = "http://localhost:11001/data"

[grpc.services.storageprovider.drivers.owncloud]
datadirectory = "/var/tmp/reva/data"
redis = "redis:6379"
userprovidersvc = "localhost:18000"

[http]
address = "0.0.0.0:11001"

[http.services.dataprovider]
driver = "owncloud"
temp_folder = "/var/tmp/reva/tmp"

[http.services.dataprovider.drivers.owncloud]
datadirectory = "/var/tmp/reva/data"
