// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// Blobstore is an autogenerated mock type for the Blobstore type
type Blobstore struct {
	mock.Mock
}

// Upload provides a mock function with given fields: key, reader
func (_m *Blobstore) Upload(key string, reader io.Reader) error {
	ret := _m.Called(key, reader)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, io.Reader) error); ok {
		r0 = rf(key, reader)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
