// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	providerv1beta1 "github.com/cs3org/go-cs3apis/cs3/storage/provider/v1beta1"
	mock "github.com/stretchr/testify/mock"

	s3ng "github.com/cs3org/reva/pkg/storage/fs/s3ng"
)

// PermissionsChecker is an autogenerated mock type for the PermissionsChecker type
type PermissionsChecker struct {
	mock.Mock
}

// HasPermission provides a mock function with given fields: ctx, n, check
func (_m *PermissionsChecker) HasPermission(ctx context.Context, n *s3ng.Node, check func(*providerv1beta1.ResourcePermissions) bool) (bool, error) {
	ret := _m.Called(ctx, n, check)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, *s3ng.Node, func(*providerv1beta1.ResourcePermissions) bool) bool); ok {
		r0 = rf(ctx, n, check)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *s3ng.Node, func(*providerv1beta1.ResourcePermissions) bool) error); ok {
		r1 = rf(ctx, n, check)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
