// Copyright 2018-2022 CERN
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// In applying this license, CERN does not waive the privileges and immunities
// granted to it by virtue of its status as an Intergovernmental Organization
// or submit itself to any jurisdiction.

// Code generated by mockery v2.40.2. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// Blobstore is an autogenerated mock type for the Blobstore type
type Blobstore struct {
	mock.Mock
}

type Blobstore_Expecter struct {
	mock *mock.Mock
}

func (_m *Blobstore) EXPECT() *Blobstore_Expecter {
	return &Blobstore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: spaceID, blobID
func (_m *Blobstore) Delete(spaceID string, blobID string) error {
	ret := _m.Called(spaceID, blobID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(spaceID, blobID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Blobstore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Blobstore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - spaceID string
//   - blobID string
func (_e *Blobstore_Expecter) Delete(spaceID interface{}, blobID interface{}) *Blobstore_Delete_Call {
	return &Blobstore_Delete_Call{Call: _e.mock.On("Delete", spaceID, blobID)}
}

func (_c *Blobstore_Delete_Call) Run(run func(spaceID string, blobID string)) *Blobstore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Blobstore_Delete_Call) Return(_a0 error) *Blobstore_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Blobstore_Delete_Call) RunAndReturn(run func(string, string) error) *Blobstore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Download provides a mock function with given fields: spaceID, blobID, blobSize
func (_m *Blobstore) Download(spaceID string, blobID string, blobSize int64) (io.ReadCloser, error) {
	ret := _m.Called(spaceID, blobID, blobSize)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, int64) (io.ReadCloser, error)); ok {
		return rf(spaceID, blobID, blobSize)
	}
	if rf, ok := ret.Get(0).(func(string, string, int64) io.ReadCloser); ok {
		r0 = rf(spaceID, blobID, blobSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, int64) error); ok {
		r1 = rf(spaceID, blobID, blobSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Blobstore_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type Blobstore_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - spaceID string
//   - blobID string
//   - blobSize int64
func (_e *Blobstore_Expecter) Download(spaceID interface{}, blobID interface{}, blobSize interface{}) *Blobstore_Download_Call {
	return &Blobstore_Download_Call{Call: _e.mock.On("Download", spaceID, blobID, blobSize)}
}

func (_c *Blobstore_Download_Call) Run(run func(spaceID string, blobID string, blobSize int64)) *Blobstore_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *Blobstore_Download_Call) Return(_a0 io.ReadCloser, _a1 error) *Blobstore_Download_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Blobstore_Download_Call) RunAndReturn(run func(string, string, int64) (io.ReadCloser, error)) *Blobstore_Download_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function with given fields: spaceID, blobID, blobSize, source
func (_m *Blobstore) Upload(spaceID string, blobID string, blobSize int64, source string) error {
	ret := _m.Called(spaceID, blobID, blobSize, source)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, int64, string) error); ok {
		r0 = rf(spaceID, blobID, blobSize, source)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Blobstore_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type Blobstore_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - spaceID string
//   - blobID string
//   - blobSize int64
//   - source string
func (_e *Blobstore_Expecter) Upload(spaceID interface{}, blobID interface{}, blobSize interface{}, source interface{}) *Blobstore_Upload_Call {
	return &Blobstore_Upload_Call{Call: _e.mock.On("Upload", spaceID, blobID, blobSize, source)}
}

func (_c *Blobstore_Upload_Call) Run(run func(spaceID string, blobID string, blobSize int64, source string)) *Blobstore_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(int64), args[3].(string))
	})
	return _c
}

func (_c *Blobstore_Upload_Call) Return(_a0 error) *Blobstore_Upload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Blobstore_Upload_Call) RunAndReturn(run func(string, string, int64, string) error) *Blobstore_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewBlobstore creates a new instance of Blobstore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBlobstore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Blobstore {
	mock := &Blobstore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
