[shared]
jwt_secret = "jwt_secret"

# services to enable
[grpc.services.gateway]
commit_share_to_storage_grant = true
commit_share_to_storage_ref = true

[grpc.services.storageregistry]
[grpc.services.storageregistry.drivers.static]
home_provider = "/home"

[grpc.services.authregistry.drivers.static.rules]
oidcmapping = "localhost:13000"

[grpc.services.storageregistry.drivers.static.rules."/home"]
address = "localhost:17000"
[grpc.services.storageregistry.drivers.static.rules."/reva"]
address = "localhost:18000"
[grpc.services.storageregistry.drivers.static.rules."123e4567-e89b-12d3-a456-426655440000"]
address = "localhost:18000"

[grpc.services.authregistry]
[grpc.services.usershareprovider]
[grpc.services.groupprovider]
[grpc.services.publicshareprovider]
[grpc.services.ocmcore]

[grpc.services.ocmshareprovider]
gateway_addr = "0.0.0.0:19000"

[grpc.services.ocminvitemanager]
[grpc.services.ocmproviderauthorizer]

[http.services.datagateway]
[http.services.prometheus]
[http.services.ocmd]
[http.services.ocdav]
[http.services.ocs]
