[http]
address = "0.0.0.0:9600"

[http.services.accounts]
# All notification emails are sent to this email
notifications_mail = "science.mesh@example.com"

# Set up the storage driver
[http.services.accounts.storage]
driver = "file"
[http.services.accounts.storage.file]
file = "/var/revad/accounts.json"

# The SMTP server used for sending emails
[http.services.accounts.smtp]
sender_mail = "science.mesh@example.com"
smtp_server = "mail.example.com"
smtp_port = 25
disable_auth = true
