version: '2'

services:

  ocdavsvc:
    build: "../../"
    volumes:
     - "./configs/ocdavsvc.toml:/etc/revad/revad.toml"
    ports:
     - "8080:9998"

  storageprovidersvc:
    build: "../../"
    volumes:
     - "./configs/storageprovidersvc.toml:/etc/revad/revad.toml"
    ports:
     - "9999:9999"

  storagebrokersvc:
    build: "../../"
    volumes:
     - "./configs/storagebrokersvc.toml:/etc/revad/revad.toml"
    ports:
     - "7777:9999"
