[http]
address = "0.0.0.0:5550"

[http.services.metrics]
metrics_data_driver_type = "xcloud"
metrics_record_interval = 5000
xcloud_instance = "http://localhost"
xcloud_interval = 5
xcloud_catalog = 'https://sciencemesh-test.uni-muenster.de/api/mentix/sites?action=register'

[http.services.prometheus]
