name: Docker
on:
  workflow_call:
    inputs:
      file:
        required: true
        type: string
      tags:
        type: string
      load:
        type: boolean
      push:
        type: boolean
      platforms:
        type: string

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Set up QEMU
        if: inputs.platforms != ''
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        if: inputs.push
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build ${{ inputs.push && 'and push' || '' }} ${{ inputs.tags }} Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ inputs.file }}
          tags: ${{ inputs.tags }}
          load: ${{ inputs.load }}
          push: ${{ inputs.push }}
          platforms: ${{ inputs.platforms }}
      - name: Upload ${{ inputs.tags }} Docker image to artifacts
        uses: ishworkh/docker-image-artifact-upload@v1
        if: inputs.load
        with:
          image: ${{ inputs.tags }}
          retention_days: '1'
