name: golangci-lint
on:
  pull_request:
    paths-ignore:
      - ".github/**"
      - "Makefile"
      - "tools/**"
      - "docs/**"
      - "tests/**"
      - ".drone.star"
      - ".drone.env"
      - ".fossa.yml"
  workflow_dispatch:

jobs:
  golangci:
    name: lint
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Setup Go environment
        uses: actions/setup-go@v3.3.0
        with:
          go-version-file: go.mod
      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1
      - name: Run golangci-lint
        run: $(go env GOPATH)/bin/golangci-lint run
