name: Test
on:
  pull_request:
  push:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: false
      - name: Test
        run: make test-go
        env:
          COVER_PROFILE: ${{ github.event_name == 'push' && 'coverage.out' || '' }}
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        if: github.event_name == 'push'
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.out
          force-coverage-parser: go
  docker:
    strategy:
      fail-fast: false
      matrix:
        file: [docker/Dockerfile.reva, docker/Dockerfile.revad-eos, docker/Dockerfile.revad-ceph]
    uses: ./.github/workflows/docker.yml
    with:
      file: ${{ matrix.file }}
  docker-revad:
    name: docker (docker/Dockerfile.revad)
    uses: ./.github/workflows/docker.yml
    with:
      file: docker/Dockerfile.revad
      load: true
  docker-revad-eos:
    name: docker (docker/Dockerfile.revad-eos)
    uses: ./.github/workflows/docker.yml
    with:
      file: docker/Dockerfile.revad-eos
      load: false
  litmus:
    needs:
      - docker-revad-eos
    strategy:
      fail-fast: false
      matrix:
        test: [litmus-1, litmus-2]
    uses: ./.github/workflows/compose.yml
    with:
      test: ${{ matrix.test }}
