name: Test
on:
  pull_request:
  push:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: false
      - name: Test
        run: make test-go
        env:
          COVER_PROFILE: ${{ github.event_name == 'push' && 'coverage.out' || '' }}
