name: Test
on:
  pull_request:
  push:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  integration:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: false
      - name: Test integration
        run: make test-integration
        env:
          REDIS_ADDRESS: redis:6379
          SQL_USERNAME: root
          SQL_PASSWORD: my-secret-pw
          SQL_ADDRESS: localhost:3306
          SQL_DBNAME: reva
    services:
      redis:
        image: registry.cern.ch/docker.io/webhippie/redis
      mysql:
        image: mysql
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: my-secret-pw
          MYSQL_DATABASE: reva
  docker:
    strategy:
      fail-fast: false
      matrix:
        file: [docker/Dockerfile.reva, docker/Dockerfile.revad-eos, docker/Dockerfile.revad-ceph]
    uses: ./.github/workflows/docker.yml
    with:
      file: ${{ matrix.file }}
  docker-revad:
    name: docker (docker/Dockerfile.revad)
    uses: ./.github/workflows/docker.yml
    with:
      file: docker/Dockerfile.revad
      load: true
  docker-revad-eos:
    name: docker (docker/Dockerfile.revad-eos)
    uses: ./.github/workflows/docker.yml
    with:
      file: docker/Dockerfile.revad-eos
      load: false
  litmus:
    needs:
      - docker-revad-eos
    strategy:
      fail-fast: false
      matrix:
        test: [litmus-1, litmus-2]
    uses: ./.github/workflows/compose.yml
    with:
      test: ${{ matrix.test }}
