[shared]
gatewaysvc = "localhost:17000"

[grpc]
address = "localhost:17010"

[grpc.services.storageprovider]
driver = "ocmreceived"
mount_path = "/sciencemesh"
mount_id = "sciencemesh"
data_server_url = "http://localhost:17011/data"

[http]
address = "localhost:17011"

[http.services.dataprovider]
driver = "ocmreceived"
